- type: job
  id: SeniorEngineer
  name: job-name-senior-engineer
  description: job-description-senior-engineer
  playTimeTracker: JobSeniorEngineer
  requirements:
    - !type:RoleTimeRequirement
      role: JobAtmosphericTechnician
      time: 10800 #2 hrs
    - !type:RoleTimeRequirement
      role: JobStationEngineer
      time: 10800 #3 hrs
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 36000 #10 hrs
  startingGear: SeniorEngineerGear
  icon: "JobIconSeniorEngineer"
  supervisors: job-supervisors-ce
  radioBold: true
  access:
  - Maintenance
  - Engineering
  - External
  - Atmospherics

- type: startingGear
  id: SeniorEngineerGear
  equipment:
    head: ClothingHeadHatBeretEngineering
    jumpsuit: ClothingUniformJumpsuitSeniorEngineer
    back: ClothingBackpackEngineeringFilled
    shoes: ClothingShoesBootsWork
    id: SeniorEngineerPDA
    eyes: ClothingEyesGlassesMeson
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineering
  innerClothingSkirt: ClothingUniformJumpskirtSeniorEngineer
  satchel: ClothingBackpackSatchelEngineeringFilled
  duffelbag: ClothingBackpackDuffelEngineeringFilled
